### PR TITLE
Logging fixes

### LINKED ISSUE #1030: logging fixes
PR #1025 incorrectly reset the `name` variable which is required for logging the program name.

Also, all log entries should specify the program PID.

### PR DESCRIPTION
**Pull request by jodh-intel**
logging: Add name to all log calls

Fixed a bug whereby PR #1025 created a `name` variable that masked the
main variable of the same name (containing the program name). Changed
the logic slightly so that all log entries now include the program name.

logging: Add PID field to logs

Add process ID to log entries.

Fixes #1030.

Signed-off-by: James O. D. Hunt <james.o.hunt@intel.com>

### CODE REVIEW

File: main.go [hunk 1]
```diff
@@ -204,9 +208,9 @@ func beforeSubcommands(context *cli.Context) error {
 
 	// Add the name of the sub-command to each log entry for easier
 	// debugging.
-	name := context.Args().First()
-	if context.App.Command(name) != nil {
-		ccLog = ccLog.WithField("command", name)
+	cmdName := context.Args().First()
+	if context.App.Command(cmdName) != nil {
+		ccLog = ccLog.WithField("command", cmdName)
```
Comment (devimc) [inline main.go]: Q. depending of the project, would `cmdName` be `cc-runtime` or `kata-runtime`?

Comment (devimc) [reply main.go]: ohh no, this is the command, like `create` , `start` , etc

File: main.go [hunk 2]
```diff
@@ -141,7 +141,11 @@ var savedCLIVersionPrinter = cli.VersionPrinter
 var savedCLIErrWriter = cli.ErrWriter
 
 func init() {
-	ccLog = logrus.WithField("source", "runtime")
+	ccLog = logrus.WithFields(logrus.Fields{
+		"name":   name,
+		"source": "runtime",
```
Comment (devimc) [inline main.go]: I wonder if this should be more specific, like `kata-runtime` or `cc-runtime`

**Comment by devimc** [comment]
dismiss my comments

LGTM
