### PR TITLE
Unit test coverage fixes

### LINKED ISSUE #759: Increase unit-test coverage (again)
Due to all the problems we've seen with coveralls recently (see https://github.com/clearcontainers/jenkins/issues/9), the unit test coverage level has slipped by 3%, so fix it.

### PR DESCRIPTION
**Pull request by jodh-intel**
tests: Increase unit test coverage
    
Add new tests to improve the overall unit-test coverage.
    
Fixes #759.

### CODE REVIEW

**Comment by sboeuf** [comment]
LGTM

**Comment by jodh-intel** [comment]
@grahamwhaley - could you take a squizz at this PR?

Coveralls report: https://coveralls.io/jobs/30598315

File: config.go [hunk 1]
```diff
@@ -226,12 +226,6 @@ func newQemuHypervisorConfig(h hypervisor) (vc.HypervisorConfig, error) {
 	kernelParams := h.kernelParams()
 	machineType := h.machineType()
 
-	for _, file := range []string{hypervisor, kernel, image} {
```
Comment (grahamwhaley) [inline config.go]: presume you found this as the coverage said it was not covered, and you could not make it so as the upper layers stopped you getting this far :-)

File: cc-env_test.go [hunk 2]
```diff
@@ -432,6 +432,74 @@ func TestCCEnvGetEnvInfo(t *testing.T) {
...
+func TestCCEnvGetEnvInfoNoHypervisorVersion(t *testing.T) {
+	assert := assert.New(t)
+
+	tmpdir, err := ioutil.TempDir("", "")
+	if err != nil {
+		panic(err)
+	}
+	defer os.RemoveAll(tmpdir)
+
+	const logFile = "/tmp/file.log"
```
Comment (grahamwhaley) [inline cc-env_test.go]: I see a few of these, and it feels like maybe this is wired somewhere else as well - is this something we can lift out to a single place? (but tbh, I fully expect you would have done that if it were possible).

File: cc-env_test.go [hunk 3]
```diff
@@ -855,6 +923,72 @@ func TestCCEnvHandleSettings(t *testing.T) {
 	assert.NoError(t, err)
 }
 
+func TestCCEnvHandleSettingsInvalidShimConfig(t *testing.T) {
+	assert := assert.New(t)
+
+	tmpdir, err := ioutil.TempDir("", "")
+	if err != nil {
+		panic(err)
```
Comment (grahamwhaley) [inline cc-env_test.go]: `panic` feels a bit harsh - OK, I know this is like a moderately fatal system error, and not strictly a test failure, but I wonder if a `Fatal` from the test suite might be more appropriate? I defer to your knowledge on that though.

File: delete_test.go [hunk 4]
```diff
@@ -501,3 +501,121 @@ func TestDeleteCLIFunction(t *testing.T) {
...
+	}
+
+	pod.MockContainers = []*vcMock.Container{
+		{
+			MockID:  testContainerID,
+			MockPod: pod,
+		},
+	}
+
+	/*
```
Comment (grahamwhaley) [inline delete_test.go]: commented out block deliberate?

**Comment by grahamwhaley** [comment]
and just confirm, I believe coveralls is reporting a 94->97% bump

File: cc-env_test.go (hunk 2 above)
Comment (jodh-intel) [reply cc-env_test.go]: We probably could get rid of some of those. I do think we could do with another test sprint since although our coverage level is high, there is still quite a bit of refactoring we could do tbh.

File: cc-env_test.go (hunk 3 above)
Comment (jodh-intel) [reply cc-env_test.go]: Fixed - it was a cut'n'paste from other (older) tests that still do call `panic()` (see sprint idea above :)

File: config.go (hunk 1 above)
Comment (jodh-intel) [reply config.go]: yes, `go test` discovered this was redundant code.

File: delete_test.go (hunk 4 above)
Comment (jodh-intel) [reply delete_test.go]: Oops. fixed.
