### PR TITLE
exec: Fix "docker exec --user"

### LINKED ISSUE #867: exec should not use the OCI `Username` value
`exec.go` uses `params.ociProcess.User.Username`. This is at best confusing since `Username` is a [Windows-specific](https://github.com/opencontainers/runtime-spec/blob/master/config.md#windows-user) value.

Once the changes on https://github.com/containers/virtcontainers/pull/522 land in the virtcontainers `master` branch, we need to re-vendor that into the runtime then change `execute()` and `generateExecParams()` to only use `params.ociProcess.User.uid`.

See:

- https://github.com/containers/virtcontainers/pull/522#discussion_r157538887

### PR DESCRIPTION
**Pull request by jodh-intel**
Fix running `docker exec` with the `--user=` option. Previously,
specifying `--user=` with any user (or user and group) would be ignored
and the workload would run as `root` (`UID`+`GID`). This was because the
runtime was setting the user to run the workload from the `Username`
field in the OCI `Process.User` struct. However, that field is
Windows-only so the value was always zero, denoting `root`.

Fixes #867.

Signed-off-by: James O. D. Hunt <james.o.hunt@intel.com>

### CODE REVIEW

File: exec.go [hunk 1]
```diff
@@ -225,11 +225,17 @@ func execute(context *cli.Context) error {
 		return err
 	}
 
+	user := fmt.Sprintf("%d:%d", params.ociProcess.User.UID, params.ociProcess.User.GID)
+
+	if params.ociProcess.User.Username != "" {
+		user = params.ociProcess.User.Username
```
Comment (sboeuf) [inline exec.go]: Are you sure we want to default to this in case we don't have anything provided. I think we should force `0:0`. This should be cleaner than to expect this `Username` to be 0 in order to set the user as root.

Comment (jodh-intel) [reply exec.go]: I'm not sure I understand - the code will default the the UID+GID provided by the OCI config file, but if the user specifies `--user=`, we'll honour that instead. But note that the `--user=` case only applies for running `cc-runtime` "standalone" and has no impact when run under docker.

Comment (sboeuf) [reply exec.go]: Oh yes I get it. I have misread the code...

**Comment by sboeuf** [comment]
LGTM

**Comment by sboeuf** [comment]
@jodh-intel CI issue:
```
/home/jenkins/jenkins_slave/workspace/clear-containers-runtime-fedora-26-PR/go/src/github.com/clearcontainers/runtime/exec.go:164:18: "overriden" is a misspelling of "overridden"
```

**Comment by jodh-intel** [comment]
Ta - branch updated.

**Comment by jodh-intel** [comment]
Note that we need to add a test for this at some point (soon!! :), so I've raised https://github.com/clearcontainers/tests/issues/805.

@jcvenegas - it would be good to get this PR in the next release btw.

**Comment by jodh-intel** [comment]
https://github.com/clearcontainers/tests/pull/808 raised for a new test for this fix.

**Comment by jodh-intel** [comment]
Hi @grahamwhaley - could you take a look at this?

**Comment by jodh-intel** [comment]
ta.
