### PR TITLE
oci: Support containers with identical ID prefixes

### LINKED ISSUE #699: Can not run container-10 when container-1 is already running
# Description of problem
```
# cc-runtime run -b path_to_bundle container-1
# cc-runtime run -b path_to_bundle container-10
```

# Expected result
`cc-runtime list` should show both containers up and running

# Actual result

Second container start fails with the following error: `"Partial container ID not unique"`

### PR DESCRIPTION
**Pull request by sameo**
Starting 2 containers with the same ID prefixes is a valid use case.
Docker CLI supports shortened container IDs but always call the runtime
with the full and complete ID.

Fixes #699

Signed-off-by: Samuel Ortiz <sameo@linux.intel.com>

### CODE REVIEW

File: oci.go [hunk 1]
```diff
@@ -55,9 +51,6 @@ var cgroupsDirPath = "/sys/fs/cgroup"
 // An error is returned if >1 containers are found with the specified
```
Comment (sboeuf) [inline oci.go]: Please remove this comment.

File: oci.go [hunk 2]
```diff
@@ -68,29 +61,14 @@ func getContainerInfo(containerID string) (vc.ContainerStatus, string, error) {
...
-				podID = podStatus.ID
-			}
 		}
 	}
 
-	if matchFound {
-		return cStatus, podID, nil
-	}
-
 	return vc.ContainerStatus{}, "", nil
```
Comment (sboeuf) [inline oci.go]: We could add a comment saying that not finding the container ID is a valid case since this function is used for both cases (when checking if we can create a new container and when checking for a specific container).

**Comment by sboeuf** [comment]
LGTM

**Comment by devimc** [comment]
lgtm

[Approved with PullApprove](https://pullapprove.com/clearcontainers/runtime/pull-request/700/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=clearcontainers/runtime) [Approved with PullApprove](https://pullapprove.com/clearcontainers/runtime/pull-request/700/?utm_source=github-pr&utm_medium=comment-badge&utm_campaign=clearcontainers/runtime)
